name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        id: cypress
        uses: cypress-io/github-action@v5
        env:
          DEBUG: '@cypress/github-action'
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000